//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cusAuthe_Roles
    {
        public int idCusAuthe { get; set; }
        public int RoleID { get; set; }
        public string Note { get; set; }
    
        public virtual cusAuthe cusAuthe { get; set; }
        public virtual Role Role { get; set; }
    }
}
