//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDatail
    {
        public int orderID { get; set; }
        public int productID { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> intoMoney { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
