//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_list_Category
    {
        public int ID { get; set; }
        public string cateName { get; set; }
        public string cateDescription { get; set; }
    }
}
